#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from the
# Apache log file apache-access.log, and displays the occurrence
# number for each, ordered from the greatest to the lowest
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn
