#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# On the 9th iteration, it also displays "Hi"
i=0
while [ "$i" -lt 10 ]
do
	i=$((i + 1))
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
done
