#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "bad luck" on the 4th
# iteration, "good luck" on the 8th iteration, and "Best School" otherwise
i=0
while [ "$i" -lt 10 ]
do
	i=$((i + 1))
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
