#!/usr/bin/env bash
# Stores its PID in a file, loops forever and reacts to SIGTERM, SIGINT, SIGQUIT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
echo "$$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
